ministryofjustice/laa-legal-adviser-api

docker/start.sh
Ensure that app logs in /var/log/wsgi have the right ownership permissions on container startup
=> chown -R www-data:www-data /var/log/wsgi

conf/uwsgi.ini, laalaa/apps/advisers/geocoder.py
It seems that the current default of 5 seconds is too low for most of the "legal provider upload" use cases. This is evidenced by the logs of this application.
As these workers each make a request to postcodeinfo service, 10 threads tend to overwhelm the service. Reducing the concurrency count seems to be a good stopgap solution.
Once we switch providers we can probably switch this back. Or at least understand if we can do bulk latitude/longitude lookups without so many requests.
⚠️ Needs testing.
=> Reduce strain on postcodeinfo service during upload

.circleci/config.yml, .dockerignore, Dockerfile
Replaces building Docker images on-demand on self-hosted Jenkins instances with building Docker images automatically on CircleCI.
Similar solution as in https://github.com/ministryofjustice/fala/pull/7, https://github.com/ministryofjustice/cla_public/pull/730
=> Build and push Docker images on CircleCI

laalaa/apps/advisers/views.py
Prevents unauthenticated users from accessing the `/admin/upload` page.
📝 There is probably a much better idiomatic way to restrict access to all urls behind `/admin`, so please let me know 😸
I followed https://docs.djangoproject.com/en/1.11/topics/auth/default/#limiting-access-to-logged-in-users.
=> LGA-92: Enforce login when accessing the upload page

.circleci/config.yml
Replaces `/` characters with `-` characters in Docker tag names.
Currently, builds on branches that have slashes (`/`) in them will always fail the Docker build as we try to incorporate the branch names into the tags.
However, Docker specifies in https://docs.docker.com/engine/reference/commandline/tag/#usage:
> A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.
Out of these constraints, this changeset only replaces slashes with dashes.
Our current example of such branch names come from dependabot, which typically creates names like `dependabot/pip/raven-6.9.0`.
Related to …
=> Allow branches with slashes to build Docker images

README.md
Documents the release process for this application for both non-production and production releases.
🔎 Nicer link to the new section: https://github.com/ministryofjustice/laa-legal-adviser-api/blob/instructions-for-release/README.md
No
=> LGA-185: Document the staging and production release of the application

laalaa/apps/advisers/middleware.py, laalaa/settings/base.py, laalaa/urls.py
This pull requests simplifies the response of /ping.json. It returns a 200 if the server is alive.
Previous to this, `ping.json` was changed to use `moj-django-irat`. As part of this change, the response remained true to the [ping.json schema](https://github.com/ministryofjustice/ping.json/blob/master/ping.json). However, there was an existing bug where the values were not being set. We didn't attempt to fix this as part of the previous change to `moj-django-irat`. We wrongly assumed /ping.json would still return a status of `200`.
It didn't. It returned a `501` because two values were not set:
```python
if not response_data['build_date'] or not response_data['commit_id']:
response.status_code = 501
```
[See the code here](https://github.com/ministryofjustice/django-moj-irat/blob/c1588426f …
=> Simplify ping.json

laalaa/apps/advisers/middleware.py, laalaa/settings/base.py
In [a previous pull request](https://github.com/ministryofjustice/laa-legal-adviser-api/pull/63), we introduced `PingMiddleware`, and took the opportunity to switch to the new style of middleware by using the `MIDDLEWARE` setting instead of the `MIDDLEWARE_CLASSES` setting.
`PingMiddleware` was written in the new style. And the [upgrade documentation](https://docs.djangoproject.com/en/1.11/topics/http/middleware/#upgrading-middleware) suggested:
>All middleware classes included with Django are compatible with both settings.
Unfortunately, we got this error:
```
Traceback (most recent call last):
File "./laalaa/wsgi.py", line 14, in <module>
application = get_wsgi_application()
File "/usr/local/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
return …
```
=> Switch back to old style of Django middleware

docker-compose.yml, laalaa/apps/advisers/healthchecks.py, laalaa/settings/base.py
This pull request injects the django app config into the celery app that is started in the healthcheck. Before this change was made, the healthcheck wrongly reported that a connection to celery couldn't be made.
I added to the `docker-compose.yml` in order to easily run and test the app inside a docker container.
`MIDDLEWARE` was changed back to `MIDDLEWARE_CLASSES` - see https://github.com/ministryofjustice/laa-legal-adviser-api/pull/65 for reasons.
=> Inject django config into celery

.circleci/config.yml, .circleci/define_build_environment_variables, .circleci/tag_and_push_docker_image
This pull requests pushes the built docker image to an additional docker registry, AWS ECR, hosted under the `mojds-platforms-integration` account.
It reuses script `tag_and_push_docker_image` from FALA.
=> Push docker image to ECR repo

.circleci/config.yml, laalaa/apps/advisers/tasks.py
Hotfix to revert string normalisation on `psql_command`
Configure string normalisation skip in lint job
=> Revert string normalisation on psql_command

.circleci/config.yml, .circleci/define_build_environment_variables, .circleci/deploy_to_kubernetes, .circleci/notify_slack_channel, .circleci/tag_and_push_docker_image, kubernetes_deploy/staging/deployment.yml, kubernetes_deploy/staging/ingress.yml, kubernetes_deploy/staging/service.yml
- Modifies the circleci build process to take the ECR region from env vars rather than hard-coded to eu-west-1
- Adds steps to the circleci workflow to deploy to staging using Kubernetes, after a confirmation step (the pods currently fail with a `CreateContainerConfigError` but I think that's reaching into the scope of future tickets rather than the environment and integration)
Uses a number of environment variables that have been added on circleci:
- `AWS_ACCESS_KEY_ID` From `ecr-repo-laa-legal-adviser-api` Kubernetes secret
- `AWS_DEFAULT_REGION` `eu-west-2` here
- `AWS_SECRET_ACCESS_KEY` From `ecr-repo-laa-legal-adviser-api` Kubernetes secret
- `ECR_DOCKER_REPO_BASE` From `ecr-repo-laa-legal-adviser-api` Kubernetes secret
- `ECR_ENDPOINT` Same as the value of `ECR_DOCKER_REPO_BASE` up …
=> LGA-531 - Integrate with new staging environment via Circle

README.md
This pull request adds extra details to the installation process. PostgreSQL also includes a POSTGIS extension which requires you to install gdal and libgeoip with Homebrew. 
Once you have installed this you then need to edit your .bash_profile so that you can run the package's programs from the command-line. 
=> Add more more detail to the installation in the Readme

kubernetes_deploy/staging/deployment.yml
Sets Sentry DSN and database credentials in Kubernetes deploy
Not all are secret, but they're all specific to a given deployment (ie
not just a staging environment, but a particular staging environment)
Config not copied from template deploy:
- ADDRESSFINDER_API_TOKEN - No longer use addressfinder
- ADDRESSFINDER_API_HOST - No longer use addressfinder
- POSTCODEINFO_API_TOKEN - No longer use postcodeinfo
- POSTCODEINFO_AUTH_TOKEN - No longer use postcodeinfo
- RABBITMQ_USER - We're going to be changing our MQ setup
- RABBITMQ_PASS - We're going to be changing our MQ setup
- HOST_IP - Don't know what this needs set to, if anything
=> LGA-534: Add env vars to set during deployment, from secrets

Dockerfile, docker/setup_postgres.sh
Specifies a non-root ID for the user that we run the app as
Also fixes the fallback when DB_NAME isn't set (eg by our cloud formation template deploy), which had an error in it.
The user ID must be specified numerically, due to the constraint in the platform: https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#how-to-adapt-to-the-pod-security-policies
=> LGA-643 - Non root container user

kubernetes_deploy/development/deployment.yml, kubernetes_deploy/development/ingress.yml, kubernetes_deploy/development/service.yml
Adds configuration for deploying the app to a local (development) kubernetes cluster, with containers for the database and mq components (which would be external services in other environments).
=> LGA-648 - Add configuration for deploying to local kubernetes

.circleci/deploy_to_kubernetes, kubernetes_deploy/development/collect-static-job.yml, kubernetes_deploy/development/migrate-db-job.yml, kubernetes_deploy/staging/collect-static-job.yml, kubernetes_deploy/staging/migrate-db-job.yml
Builds on #121 
Adds a Job to run database migrations
Renames the existing Job file to reflect that we're not putting multiple Job resources in one file as previously planned, as that didn't work well with how we apply them
=> LGA-645 - Run laalaa db migrations in a Job

kubernetes_deploy/development/queue_worker_deployment.yml, kubernetes_deploy/production/queue_worker_deployment.yml, kubernetes_deploy/staging/queue_worker_deployment.yml
Sets the liveness and readiness probes for the staging and production queue worker pods
Fixes the liveness and readiness probes for the development queue worker pods
=> LGA-666 - Set livenessProbe and readinessProbe for queue worker pods

docker/run_worker.sh
These are the recommended settings for cloudamqp.com, to avoid burning
through usage limits with heartbeats and other meta tasks. Apparently
the way they manage connections does not benefit from having these.
This code has already been merged into another feature branch, but that hasn't reached `master` yet, so this PR is to put this change straight into `master` without having to wait.
Required.
=> LGA-708 - Remove celery heartbeat and make it quieter

README.md, docker-compose.yml, docker/run_worker.sh, kubernetes_deploy/development/deployment.yml, kubernetes_deploy/development/queue_worker_deployment.yml, kubernetes_deploy/development/service.yml, kubernetes_deploy/development/shared_services_deployment.yml, kubernetes_deploy/production/deployment.yml, kubernetes_deploy/production/queue_worker_deployment.yml, kubernetes_deploy/staging/deployment.yml, kubernetes_deploy/staging/queue_worker_deployment.yml, laalaa/apps/advisers/tasks.py, laalaa/celery.py, laalaa/settings/base.py, requirements/base.txt, setup_postgres.sh
Reconfigures the application to use Redis as the Celery broker.
Cloud Platform staging namespace has been provisioned with Amazon ElastiCache for Redis to match this change:
- https://github.com/ministryofjustice/cloud-platform-environments/pull/1182
- https://github.com/ministryofjustice/cloud-platform-environments/pull/1184
Please review commit-by-commit to review the intent in the commit messages.
Performance with node_type cache.t2.micro
redis-cp: 10 minutes with 8 workers for 4700 records, 470/minute
amqp-td: 2.5 minutes with 8 workers for 4700 records, 1880/minute
redis-cp is 4x slower than amqp-td but at this stage we are trying to get the application to work.
Further work is required to address performance when needed
=> LGA-820 - Switch to Redis

kubernetes_deploy/production/deployment.yml, kubernetes_deploy/production/queue_worker_deployment.yml
Update production config to use redis celery broker
Cloud Platform staging namespace has been provisioned with Amazon ElastiCache for Redis to match this change:
https://github.com/ministryofjustice/cloud-platform-environments/pull/1453
Performance with node_type cache.t2.medium
redis-cp: 10 minutes with 8 workers for 4700 records, 470/minute
Strangely performance did not improve from staging (https://github.com/ministryofjustice/laa-legal-adviser-api/pull/136) even when running on a more powerful node_type
=> LGA-849 - Update production config to use redis celery broker

requirements/base.txt
Downgrade kombu from 4.6.5 to 4.6.3 to fix issue with redis keys getting evicted which resulted in the following error:
> Control command error: OperationalError(u"\nCannot route message for exchange u'reply.celery.pidbox': Table empty or key no longer exists.\nProbably the key (u'_kombu.binding.reply.celery.pidbox') has been removed from the Redis database.\n",)
Fixed adopted from https://github.com/celery/kombu/issues/1063
=> Downgrade kombu from 4.6.5 to 4.6.3

laalaa/apps/advisers/healthchecks.py
Configures the `/healthcheck.json` URL to use the new configuration style of Celery 4 under Django.
In bed52d9c60b00be751a6a9a6fc78b333fc5bccf6, I had to change the configuration to be compatible with Django. I completely missed this part.
Unfortunately, the test for this module starts with mocking the `get_stats()` function, where this code exists, so I am at loss at how to test this.
For now, I think we can expose `/healthcheck.json` on the staging environment which would have helped detect this problem. In the long-term, we will use a separate healthcheck for the worker processes.
There is still the question whether the "webapp" can connect to the "broker" which I feel could be tackled by this app's healthcheck.
Thoughts for later, I suppose.
=> LGA-820, LGA-849: Load namespaced Celery configuration in healthcheck

docker/setup_postgres.sh, kubernetes_deploy/development/deployment.yml, kubernetes_deploy/development/migrate-db-job.yml, kubernetes_deploy/development/queue_worker_deployment.yml, kubernetes_deploy/production/deployment.yml, kubernetes_deploy/production/migrate-db-job.yml, kubernetes_deploy/production/queue_worker_deployment.yml, kubernetes_deploy/staging/deployment.yml, kubernetes_deploy/staging/migrate-db-job.yml, kubernetes_deploy/staging/queue_worker_deployment.yml, laalaa/settings/base.py, requirements/base.txt
Removes the multiple $DB_* environment variables and replaces them with one $DATABASE_URL connection string environment variable.
The `psql` command doesn't seem to work with the `postgis://` connection string but works with `postgres://`. So I had to change `psql` command to `psql "${DATABASE_URL/postgis/postgres}"` in the `docker/setup_postgres.sh` script
=> LGA-649 - Use DATABASE_URL connection string

.circleci/config.yml, Dockerfile
I came across [trivy](https://github.com/aquasecurity/trivy) in ThoughtWorks' technology radar:
https://www.thoughtworks.com/radar/tools?blipid=201911077
> Our teams particularly like Trivy, a vulnerability scanner for
> containers, because it's easier to set up than other tools, thanks to
> it shipping as a stand-alone binary.
Stand-alone setup sounded like a good fit for our use-case, so I decided
to give it a try.
Currently, only critical severity problems cause a pipeline failure and
_only_ production requires the scan to pass.
=> Add Docker security scanning with trivy

requirements/base.txt
Reverts ministryofjustice/laa-legal-adviser-api#138
Broker production with the following errors:
`[pid: 51| GET /admin/import-progress/ => generated 27 bytes in 207 msecs (HTTP/1.1 500) 5 headers in 173 bytes (1 switches on core 0)
File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
response = view_func(request, *args, **kwargs)
File "/home/app/laalaa/apps/advisers/views.py", line 196, in import_progress
"task": …
=> Revert "[Security] Bump django from 1.11.20 to 1.11.23"

.circleci/config.yml, Dockerfile, laalaa/apps/advisers/middleware.py, laalaa/apps/advisers/migrations/0001_initial.py, laalaa/apps/advisers/migrations/0004_auto_20150407_1228.py, laalaa/apps/advisers/migrations/0006_import.py, laalaa/apps/advisers/migrations/0007_auto_20151014_1428.py, laalaa/apps/advisers/models.py, laalaa/apps/advisers/tasks.py, laalaa/apps/advisers/tests/test_geocoder.py, laalaa/apps/advisers/urls.py, laalaa/apps/advisers/views.py, laalaa/settings/base.py, laalaa/urls.py, requirements/base.txt
- Change MIDDLEWARE_CLASSES to MIDDLEWARE in the settings
- Upgraded advisers.middleware.PingMiddleware to work with django 2.2 middleware spec
- Added on_delete=models.CASCADE to all ForeignKey and OneToOne model fields. Including existing migrations
- Removed SessionAuthenticationMiddleware middleware from settings. It provided no functionality since session authentication is unconditionally enabled in Django 1.10
- Removed GeoManager as parent of LocationManager as all methods have been deprecated and replaced by equivalent database functions.  
Had to use http://dl-cdn.alpinelinux.org/alpine/v3.10/main python3-dev=3.7.5-r1 repository to install python 3.7 instead of latest version in the edge repository which at the time of this PR is 3.8. This also installs pip3 so we didn't need …
=> LGA-946 - Django 2.2 upgrade

.circleci/config.yml, .coveragerc, .gitignore, README.md, laalaa/settings/base.py, requirements/dev.txt
Wraps test running in coverage
Stores the output on circleci as artifacts
Sends coverage results to coveralls.io
Adds a coveralls badge to the readme
Generates and stores test metadata in xml format for CircleCI to monitor
Based on https://github.com/ministryofjustice/cla_backend/pull/583
=> LGA-696 - Code coverage on CircleCI

Dockerfile, kubernetes_deploy/development/deployment.yml, kubernetes_deploy/development/queue_worker_deployment.yml, kubernetes_deploy/development/shared_services_deployment.yml, kubernetes_deploy/production/deployment.yml, kubernetes_deploy/production/ingress.yml, kubernetes_deploy/production/queue_worker_deployment.yml, kubernetes_deploy/staging/deployment.yml, kubernetes_deploy/staging/ingress.yml, kubernetes_deploy/staging/queue_worker_deployment.yml, requirements/dev.txt
Switches some kubernetes resources from old versions to their newer ones (in different resource groups).
These changes are backwards compatible, and the server will use any versions it supports interchangeably.
Updates Python version and one package requirement to allow the image to still build.
=> LGA-1281 - Upgrade kubernetes apis

kubernetes_deploy/production/queue_worker_deployment.yml, kubernetes_deploy/staging/collect-static-job.yml, kubernetes_deploy/staging/deployment.yml, kubernetes_deploy/staging/migrate-db-job.yml, kubernetes_deploy/staging/queue_worker_deployment.yml, laalaa/celery.py, laalaa/settings/base.py, requirements/base.txt
Replaces the Raven library with the more modern Sentry SDK
This repo is a nice simple one, doesn't seem to have presented anything we didn't already deal with for `cla_backend`
Sets the ENV env var more consistently, as it's now used for more than just ensuring an environment is not production for a particular job.
=> LGA-1507 - Sentry SDK

.circleci/config.yml, Dockerfile
Upgrade python package to python3.8.7-r2 to fix [CVE-2021-3177]
Bug as reported https://bugs.python.org/issue42938
The bug was fixed in the [python3.8.7-r2 package](https://pkgs.alpinelinux.org/package/edge/main/x86_64/python3) by this comment https://git.alpinelinux.org/aports/commit/?id=5e7e1c23fb66dbdbd37939157ceb2ea94535de1a
=> LGA-1634 - Upgrade python package to python3.8.7-r2 to fix [CVE-2021-3177]

laalaa/apps/advisers/management/commands/seed.py, laalaa/apps/advisers/tests/test_seed.py
- Add all fixtures in `apps/advisers/fixtures` directory during seeding
- Fixtures directory includes `initial_advisers.json` and `initial_categories.json`
- Add test to ensure data from both fixtures are loaded
Requires writing some tests
=> LGA-1521 Fix database seeding issues

laalaa/apps/advisers/management/commands/abort_last_import.py, laalaa/apps/advisers/management/commands/utils.py, laalaa/apps/advisers/management/commands/worker_health_checks.py, laalaa/apps/advisers/tasks.py, laalaa/apps/advisers/tests/test_commands.py
`app.control.purge()` was only removing tasks in the queue, we  needed to instead call `app.control.revoke()` to remove tasks that running/scheduled(scheduled tasks, are tasks that the worker has claimed but has not yet started working on them)
app.control.revoke(terminate=True) without an additional `signal="SIGUSR1"` parameter will cause the worker to be terminated and would raise a `billiard.exceptions.Terminated` exception that cannot be captured. See https://github.com/celery/celery/issues/2727 for more details
The `GeocoderTask` and `ProgressiveAdviserImport` celery tasks run handlers had to be wrapped in a try block to capture the `billiard.exceptions.SoftTimeLimitExceeded` exception that is raised when the tasks are revoked. The `except` block raises a `celery.exceptions.Ignore` …
=> LGA-1802 - Remove the current task as well as those that are queued

.circleci/config.yml
Remove usage of deprecated setup-kube-auth
Create reusable deploy job and both staging/production deployments use new deploy job
=> LGA-1915 - Remove setup-kube-auth

.circleci/config.yml, kubernetes_deploy/staging-live1/collect-static-job.yml, kubernetes_deploy/staging-live1/deployment.yml, kubernetes_deploy/staging-live1/ingress.yml, kubernetes_deploy/staging-live1/migrate-db-job.yml, kubernetes_deploy/staging-live1/queue_worker_deployment.yml, kubernetes_deploy/staging-live1/service.yml, kubernetes_deploy/staging/ingress.yml
Deploy staging to the new live cluster
Create new `kubernetes_deploy/staging-live1` deployment files and deploy to live-1 cluster
Deploy existing `kubernetes_deploy/staging` deployment files to new live cluster
Set `kubernetes_deploy/staging-live1` ingress weight to 0% so that it does not receive any traffic
Set `kubernetes_deploy/staging` ingress weight to 100% so that it receives all of the traffic
=> LGA-1927 deploy staging to live

docker/workers_healthcheck.sh
Remove celery status check from worker pod health checks
The command `exec celery -A laalaa status` times out on the new kubernetes live cluster.
A --timeout option has been added to the status on later version of celery
=> Remove celery status check from worker pod health checks

kubernetes_deploy/production/queue_worker_deployment.yml, kubernetes_deploy/staging/queue_worker_deployment.yml
Disable readiness and liveness probes
The probes were inconsistently(most failing) working and causing the worker pod to restart and then eventually crash.
They need to be disabled so that the monthly laalaa upload can be done.
https://dsdmoj.atlassian.net/browse/LGA-2050 has been created to investigate the probe failures and to re-enable them
=> Disable readiness and liveness probes

kubernetes_deploy/production/ingress.yml, kubernetes_deploy/staging/ingress.yml, requirements/base.txt
Updated django to 2.2.28 to fix https://avd.aquasec.com/nvd/2022/cve-2022-28346/)
Add modsec in detection only mode
Create new ingress that has spec.ingressClassName set to 'modsec' so that the new v122 ingress controller is used
The ingress `laa-legal-adviser-api` on both staging and production has had it's annotation `external-dns.alpha.kubernetes.io/aws-weight`  set to 0
When this PR is merged a new `laa-legal-adviser-api-v122` will be created with `external-dns.alpha.kubernetes.io/aws-weight` of 100
The new ingress will take a while to setup(DNS propagation), in that time the old ingress will continue to service request.
Once the new ingress is ready, the old ingress needs to be manually removed
More information can be found on the user guide …
=> LGA-2127 - Add modsec in detection only mode and created new ingress for v122

requirements/base.txt
=> Pinned version of importlib_metadata to work with python 3.7.

.circleci/config.yml, laalaa/apps/advisers/models.py, requirements/base.txt
Required.
Encountered error with cython upgrade to version 3.0. This means that pyyaml will not load.
https://github.com/yaml/pyyaml/issues/601
Had to update awscli to version 2 in order that this bug is fixed. Could not update to the latest version of 1 as this was not supported by the remote docker image we were using in circleci to create the docker image
https://github.com/aws/aws-cli/issues/5943
=> WIP: LGA-2589 Updating PROVIDER_CATEGORIES with hlpas value

laalaa/apps/advisers/models.py
Required.
Removing the letter S from the end of service.
=> LGA-2589 Remove S from the end of services

.github/CODEOWNERS
This means:
* CCQ are notified about PRs that need reviewing.
* CCQ reviews count towards being able to merge the PR (according to the branch protection that "Requires review from Code Owners")
I'm leaving Team 1 on the codeowners list, for the time being, for a handover period, or emergency help.
=> Add CCQ to CODEOWNERS

.github/CODEOWNERS
so that they stop getting notifications
=> Remove Team 1 from CODEOWNERS

README.md, laalaa/apps/advisers/geocoder.py, requirements/dev.txt
- using 'requests' `HTTPAdapter` & 'urllib3' `Retry` to up the retries to third party postcode api.
- upping the retries to 5, but happy to up this further if needed.
- also updated `pre-commit` version as was having trouble with packages 
- have used this as a [template](https://github.com/ministryofjustice/operations-engineering/blob/f83e228b056eeb84e2722e429d89498a98df56bd/services/operations_engineering_reports.py#L4)
=> EL-1644: Adding some connection retries to LAALAA Postcode lookup.

laalaa/apps/advisers/tasks.py
- Improve display of failed postcode lookup in LAALAA upload.
- This is what it looks like now:
- Based on the current way that LAALAA has set-up the DB schema, we can only get granular details from the 'OFFICE LOCATION' tab but not on 'OUTREACH SERVICE' tab.
- It’s because of an SQL statement which doesn’t copy over everything from `outreach_service` into `advisers_office table`
=> EL-1661: Improve display of failed postcode lookup in LAALAA upload

laalaa/templates/import_progress.html
- If applied, this change will stop refresh of page, remove progress bar and count once the `success` text is on the screen
- the end result will look like this after a successful upload
- n/a
=> EL-2032: Prevent page refresh when `.xlsx` upload complete, in order to copy 'postcode errors'

.github/workflows/dependanot-create-jira.yml
When dependabot opens a PR this action creates a new ticket in the backlog
there is another step to add a jira workflow to point these tickets and bring them into sprint.
successful test of the curl command and JIRA rest API:
https://dsdmoj.atlassian.net/browse/LGA-3762
=> Github action: create jira ticket when a dependabot PR is opened

.circleci/config.yml
removes the approval steps from the circleci pipeline
this repo does not need much maintenance and we dont use approval steps in our other pipelines so merges can sometimes be forgotten to be released. This is also inline with the CI/CD guardrails which prefer continuous deployment
ie. fully automated deployment pipelines
=> remove approval steps from pipeline
