ministryofjustice/laa-legal-adviser-api

- .gitignore
- Dockerfile
- conf/supervisor/conf.d/laalaa.conf
- conf/uwsgi/laalaa.ini
- docker/build.sh
- laalaa/settings/base.py
- requirements/base.txt
- Ensure nginx is running in the container
- Ensure uwsgi runs the application
- Add uwsgi and djagno application logging
- remove confd configuration
- add docker build script
> laalaa deployment config update:

- docker/build.sh
> fix docker/build.sh

- docker/start.sh
>  apply permission on /var/log/uwsgi

- laalaa/apps/advisers/views.py
Additionally don't return results without location
> Add ability to filter by categories

- laalaa/apps/healthcheck/views.py
will always fail if the DB is not present
> Removing the database healthcheck as it's pointless as Django engine

- laalaa/apps/healthcheck/views.py
- laalaa/settings/base.py
It was still checking AddressFinder, which has been replaced
> Healthcheck tests PostcodeInfo availability

- laalaa/apps/advisers/importer.py
- laalaa/apps/advisers/management/commands/load_advisers.py
- laalaa/apps/advisers/migrations/0006_import.py
- laalaa/apps/advisers/models.py
- laalaa/apps/advisers/views.py
Refactored the importer to this process:
1. Load the Excel spreadsheet into memory
2. Save each sheet to a temporary CSV file
3. Use COPY FROM to load the CSV file into the db
4. Translate the data to Django model tables using SQL
5. Geocode the postcodes and update the db
This is quite a lot faster than the previous method of parsing the Excel file
and generating Django models and adding them using the ORM.
> Refactor advisers importer

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
- Sets up @ministryofjustice/laa-get-access as code owners to this project.
- Adds a pull request template, that looks like this pull request.
> Setup code owners and pull request template

- laalaa/__init__.py
- laalaa/settings/base.py
> LGA-451 Flake8 fixes

- laalaa/apps/advisers/healthchecks.py
- laalaa/apps/advisers/tests/test_healthchecks.py
[LGA-484: Implement tests for health check](https://dsdmoj.atlassian.net/browse/LGA-484)
This pull request creates an integration test checks all health checks have pass.
It also has modified the code in the class CeleryWorkersHealthcheck, pulling out the method 'get_stats', so that it is able to be mocked inside the test. 
> LGA-484: Implement tests for health check

- .circleci/config.yml
Add `pip check` to CI test job to verify dependency compatibility.
> LGA-438 Add pip check to CI

- .circleci/deploy_to_kubernetes
- docker/local_deploy.sh
- docker/run_worker.sh
- kubernetes_deploy/development/deployment.yml
- kubernetes_deploy/development/queue_worker_deployment.yml
- kubernetes_deploy/development/service.yml
- kubernetes_deploy/development/shared_services_deployment.yml
- kubernetes_deploy/staging/queue_worker_deployment.yml
- laalaa/apps/advisers/tasks.py
- laalaa/apps/advisers/views.py
- laalaa/settings/base.py
- Added AMQP_BROKER_URL environment variable that contains AMQ broker connection string.
- Moved the conversion of the uploaded spreadsheet into database records out of the celery tasks and into the form upload submit handler so that celery worker pods do not access to the uploaded file.
- Added deployment for development queue workers.
- Created shared services deployment for development namespace to mock external services
> LGA-630 - Adding connection details

- .circleci/config.yml
- kubernetes_deploy/production/deployment.yml
- kubernetes_deploy/production/ingress.yml
- kubernetes_deploy/production/queue_worker_deployment.yml
- kubernetes_deploy/production/service.yml
Adding production deployment
We will be using the the cloud platform provided domain instead of migrating the existing domain
Created namespace in https://github.com/ministryofjustice/cloud-platform-environments/pull/805
Needs S3 bucket https://github.com/ministryofjustice/cloud-platform-environments/pull/813
> LGA-532 - kubernetes production deployment

- .circleci/config.yml
- .circleci/deploy_to_kubernetes
- Dockerfile
- conf/uwsgi.ini
- docker/collectstatic.sh
- kubernetes_deploy/development/deployment.yml
- kubernetes_deploy/development/jobs.yml
- kubernetes_deploy/development/queue_worker_deployment.yml
- kubernetes_deploy/staging/deployment.yml
- kubernetes_deploy/staging/jobs.yml
- kubernetes_deploy/staging/service.yml
- laalaa/settings/base.py
- requirements/base.txt
Configures the web app to be able to use s3 for static file storage
Makes it use s3 storage on staging (already provisioned by terraform)
Removes collecting of static files from the docker image
Collects static as part of the kubernetes deploy, as a Job, and waits for it to complete before deploying the Deployment pods
Also fixes the configuration of the kubernetes Service
> LGA-652: Finish setting up the app pods

- kubernetes_deploy/development/collect-static-job.yml
- kubernetes_deploy/development/deployment.yml
- kubernetes_deploy/development/migrate-db-job.yml
- kubernetes_deploy/development/queue_worker_deployment.yml
- kubernetes_deploy/development/service.yml
- kubernetes_deploy/development/shared_services_deployment.yml
- kubernetes_deploy/production/collect-static-job.yml
- kubernetes_deploy/production/deployment.yml
- kubernetes_deploy/production/migrate-db-job.yml
- kubernetes_deploy/production/queue_worker_deployment.yml
- kubernetes_deploy/production/service.yml
- kubernetes_deploy/staging/collect-static-job.yml
- kubernetes_deploy/staging/deployment.yml
- kubernetes_deploy/staging/migrate-db-job.yml
- kubernetes_deploy/staging/queue_worker_deployment.yml
- kubernetes_deploy/staging/service.yml
Adds the Job resources to the production environment and fixes a couple of mistakes in the Service definition
> LGA-658 - update production env

- kubernetes_deploy/staging/deployment.yml
Fixes uploads by passing the amqp secret through to the web app pods
> LGA-665 - Configure web pods to communicate with amqp

- kubernetes_deploy/production/deployment.yml
Fixes uploads by passing the amqp secret through to the web app pods
Same change as #126 but for production
> LGA-665 - Configure amqp for web pods in production deployment

- docker/run_worker.sh
Uses the command line arguments that cloudamqp recommends, to avoid using heartbeats that they don't need for their connection management and that consume our usage quotas.
> LGA-708 - reconfigure celery

- README.md
Update the README to refelct learnings about how categories are managed in LAALAA
> Update the README to refelct learnings about how categories are managed in LAALAA

- laalaa/apps/advisers/models.py
- laalaa/apps/advisers/tests/test_views.py
- laalaa/apps/advisers/urls.py
- laalaa/apps/categories/serializers.py
- laalaa/apps/categories/views.py
- laalaa/settings/base.py
Create categories endpoint
Create categories endpoint for cla_public and fala to consume 
> LGA-813 - Create categories endpoint

- .circleci/config.yml
- conf/uwsgi.ini
- docker/run.sh
- docker/setup_postgres.sh
- kubernetes_deploy/production/deployment.yml
- kubernetes_deploy/staging/deployment.yml
- laalaa/settings/base.py
This pull request removes the remnants of template-deploy-related branching in the codebase.
Please review changes commit-by-commit for further details.
> LGA-649: Remove template-deploy code

- requirements/base.txt
Reverts ministryofjustice/laa-legal-adviser-api#146
> Revert "Revert "[Security] Bump django from 1.11.20 to 1.11.23""

- README.md
- Update documentation python version to 3
- Remove old template deploy release documentation
- Add kubernetes releasing documentation
- [] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"
> Update documentation python version to 3

- laalaa/apps/advisers/models.py
Adding modern slavery category
> LGA-1534 - Adding modern slavery category

- Dockerfile
amended dockerfile to set specific python version
> LGA-1733 Update/set python version in dockerfile

- laalaa/apps/advisers/tests/test_views.py
- laalaa/templates/upload.html
I have introduced some javascript that will stop a user being able to press the submit button the upload form more than once.
> LGA 1875 stop multiple submission of upload

- laalaa/templates/upload.html
This branch adds javascript to the upload button to prevent it submitting more than once.
> LGA - 1875 - Prevent more than one upload

- docker/workers_healthcheck.sh
- kubernetes_deploy/development/queue_worker_deployment.yml
- kubernetes_deploy/production/queue_worker_deployment.yml
Fixes the probe definitions on the queue worker pods in production and dev to keep up with the script being renamed (which has already been updated on staging)
> LGA-1885 - Fix worker probes

- .circleci/config.yml
- kubernetes_deploy/production-live1/collect-static-job.yml
- kubernetes_deploy/production-live1/deployment.yml
- kubernetes_deploy/production-live1/ingress.yml
- kubernetes_deploy/production-live1/queue_worker_deployment.yml
- kubernetes_deploy/production-live1/service.yml
- kubernetes_deploy/production/ingress.yml
Deploy production to new live cluster
Remove old K8s migrate-db-jobs
> LGA-1928 Deploy production to new live cluster

- kubernetes_deploy/production-live1/ingress.yml
- kubernetes_deploy/production/ingress.yml
Send all traffic to the new live cluster
> LGA-1945 - Send all traffic to the new live cluster

- kubernetes_deploy/production/ingress.yml
- kubernetes_deploy/staging/ingress.yml
Updated the apiVersion and changed backend service descriptions as required by updated version
This project does not use helm so there are no required associated upgrades as with cla_frontend, cla_backend and cla_public
> WIP LGA-1939 Remove deprecated ingress api version

- .gitignore
- Dockerfile
- kubernetes_deploy/production/collect-static-job.yml
- kubernetes_deploy/production/deployment.yml
- kubernetes_deploy/production/migrate-db-job.yml
- kubernetes_deploy/production/queue_worker_deployment.yml
- kubernetes_deploy/staging/collect-static-job.yml
- kubernetes_deploy/staging/deployment.yml
- kubernetes_deploy/staging/migrate-db-job.yml
- kubernetes_deploy/staging/queue_worker_deployment.yml
- laalaa/settings/base.py
- requirements/base.txt
- Use short lived credentials
- Change from using celery+redis to celery+sqs like our other projects
- Adding curl-dev alpine package so that pycurl pip package can build
> LGA-2582 - Use short lived credentials

- kubernetes_deploy/production/collect-static-job.yml
- kubernetes_deploy/production/deployment.yml
- kubernetes_deploy/production/queue_worker_deployment.yml
- kubernetes_deploy/staging/collect-static-job.yml
- laalaa/settings/base.py
> Feature/lga 2582  adding irsa

- .circleci/config.yml
- .circleci/deploy_to_kubernetes
- kubernetes_deploy/production/database-migration.yml
- kubernetes_deploy/staging/database-migration.yml
- kubernetes_deploy/staging/deployment.yml
- kubernetes_deploy/staging/migrate-db-job.yml
- kubernetes_deploy/staging/queue_worker_deployment.yml
Update pipeline to use postgres 14 in staging
[LGA-2766](https://dsdmoj.atlassian.net/browse/LGA-2766)
[LGA-2766]: https://dsdmoj.atlassian.net/browse/LGA-2766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LGA-2766 - Update pipeline to use postgres 14

- kubernetes_deploy/production/deployment.yml
- kubernetes_deploy/production/migrate-db-job.yml
- kubernetes_deploy/production/queue_worker_deployment.yml
migration rds 11 to rds 14
https://dsdmoj.atlassian.net/browse/LGA-2774
> WIP: LGA-2774 adding in new database-14 url

- kubernetes_deploy/production/ingress.yml
- kubernetes_deploy/staging/ingress.yml
> LGA-1738 - Enable WAF

- laalaa/settings/base.py
- laalaa/urls.py
- requirements/base.txt
Add django metrics endpoint for prometheus scraping
> EL-1483 Add django metrics endpoint

- .circleci/config.yml
- kubernetes_deploy/staging/ingress-dashboard.yml
- kubernetes_deploy/staging/pods-dashboard.yml
Pods and ingress dashboards for LAALAA
Add /metrics endpoint to LAALAA
> El 1483 grafana dashboards

- kubernetes_deploy/staging/deployment.yml
- kubernetes_deploy/staging/pods-dashboard.yml
- laalaa/settings/base.py
LAALAA dashboards were reporting incorrect information, but resources were also a little low. Improve both of these so that data is accurate but also that service has enough resource to run effectively
> El 1496 resource spike

- .circleci/config.yml
Fix the production deployment of LAALAA
This was broken by the last commit, as we attempted to deploy the grafana dashboards when doing production deploys where they are actually only relevant to staging deploys
> El 1496 fix deployment

- .circleci/config.yml
- .circleci/define_build_environment_variables
- Updated circleci Ymal file to look at main branch instead of master
- [EL-1717](https://dsdmoj.atlassian.net/browse/EL-1717)
[EL-1717]: https://dsdmoj.atlassian.net/browse/EL-1717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EL-1717 circlci ymal update to change master to main
